spring:
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  datasource:
    url: jdbc:postgresql://localhost/work_db
    username: postgres
    password:
  mail:
    host: smtp.gmail.com
    username:
    password:
    port: 587
    protocol: smtp
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  freemarker:
    expose-request-attributes: true

server:
  port: 8090
upload:
  path: /home/nonamepc/dev_files
mail:
  debug: true
hostname: localhost:8090

recaptcha:
  secret: 6LcGmWoUAAAAAAH4m1NdWsseCOXhN9UOSOzUqgCQ
